version: '3.8'
services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "26884:26884"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26884/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "26885:26885"
    environment:
      - REACT_APP_API_URL=http://moxie.cs.oswego.edu:26884
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
