services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "26884:26884"
    networks:
      - app-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://moxie.cs.oswego.edu:26884
    ports:
      - "26885:26885"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
